name: Cambio en web.config

on:

  workflow_dispatch: #

jobs:
  modificar-webconfig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script to modify web.config
      run: |
        
        #sed -i '/<sessionState>/,/<\/sessionState>/ s/^/<!-- /; s/$/ -->/' web.config

        awk '/<sessionState>/,/<\/sessionState>/ { print "<!-- " $0 " -->" } ! /<sessionState>/,/<\/sessionState>/' web.config > web.config.tmp && mv web.config.tmp web.config

    - name: Upload modified web.config
      uses: actions/upload-artifact@v2
      with:
        name: web.config
        path: web.config
