name: Cambio en web.config

on:

  workflow_dispatch: #

jobs:
  modificar-webconfig:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script to modify web.config
      run: |
        sed -i 's/<sessionState/<!--<sessionState/g' web.config
        sed -i 's/sessionState>/sessionState>-->/g' web.config
                
    - name: Upload modified web.config
      uses: actions/upload-artifact@v2
      with:
        name: web.config
        path: web.config
